image: nixos/unstable
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
triggers: 
  - action: email
    condition: failure
    to: logins@prma.dev
  
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable 

tasks: 
  - check-flake: |
      cd prmait
      ls 
      nix flake check


