image: nixos/unstable
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
sources:
  - https://git.sr.ht/~prma/prmait
packages:
  - nixpkgs.cargo
  - nixpkgs.cargo-nextest
  - nixpkgs.cargo-clippy
  
tasks: 
  - check: |
      cd prmait
      ls 
      nix flake check
  - test: |
      cd prmait
      cargo nextest run
  - lint: |
      cd prmait
      cargo clippy


