image: nixos/unstable
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
sources:
  - https://git.sr.ht/~prma/prmait
packages:
  - nixpkgs.cargo
  - nixpkgs.cargo-nextest
  - nixpkgs.glibc

repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable 

tasks: 
  - lint: |
      cd prmait
      cargo clippy
  - test: |
      cd prmait
      cargo nextest run
  - check-flake: |
      cd prmait
      ls 
      nix flake check


