image: nixos/unstable
environment:
  NIX_CONFIG: "experimental-features = nix-command flakes"
sources:
  - https://git.sr.ht/~prma/prmait

repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable 

tasks: 
  - check-flake: |
      cd prmait
      ls 
      nix flake check


